### ISSUE TITLE
Docs would require some gazing..!

### ISSUE THREAD

**Issue by pjylkka** [virtualvivek/windows-ui#16]
Sliders page has typo on link:
It heads to https://windows-ui.github.io/docs/sliderBar.html 
but page is https://windows-ui.github.io/docs/sliderbar.html

And also - is those Icons documented somewhere?

Thank you <3

**Comment by virtualvivek** [comment]
Hi @pjylkka ,

Thanks for raising this issue.
Docs has been fixed now.
Icons has been documented now - [windows-ui/icons](https://github.com/windows-ui/icons).

Once issue resolved from your end you can close this one.
Else let me anything that is still pending [Boilerplate is still in progress from my end :) ]
