### ISSUE TITLE
Invalid css

### ISSUE THREAD

**Issue by easyontop** [virtualvivek/windows-ui#23]
text/plain: in README.md, see app-config.css.css
Expected: app-config.css

**Comment by virtualvivek** [comment]
Thanks @easyontop,

Naming has been fixed for the app-config.css file :)

**Comment by easyontop** [comment]
> Thanks @easyontop,
> 
> Naming has been fixed for the app-config.css file :)

also I think import usage should be provided as the js might not work if not put before end of body
