### ISSUE TITLE
A full dashboard app.

### ISSUE THREAD

**Issue by TheErondu** [virtualvivek/windows-ui#7]
I'm trying to make a full admin panel, the sidebar in framework.html seems to be linking to the different app sections, how do I override this and link to a different page?

**Comment by virtualvivek** [comment]
Hi @neodavids ,

I have planned to merge the `react-windows-ui` repo components with this repo to get less complicated ui and code.
Once i get complete that `react-windows-ui` repo then i will update this one also!

**Comment by virtualvivek** [comment]
Hi @TheErondu ,

A stable release has been published now.
`react-windows-ui` has been imported successfully as `windows-ui`.
More components added as compare to earlier version.

**Comment by TheErondu** [comment]
Thanks! trying it out now!
